# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Yer39DKcrKc-YYkY6XZ6s48mXtWiHr46
"""

import json
admin={"Admin name":"Edyoda","Admin password":"Edyoda@123"}
with open ("admin.json","w") as f:
  json.dump(admin,f)
  print("json for admin is comleted")
  print(admin)

# YOU HAVE TO DESIGN A FOOD ORDERING APP FOR RESTAURANT
import re
import json
class Restaurant:
  
  def __init__(self,name):
    self.rest_name=name
    self.Foods={}
    self.Food_id=len(self.Foods)+1
    self.ordered_item=[]
  def add_food_item(self):
    try:
      self.Name=input("Enter the Food Name: ")
      self.Quantity=input("Enter The Quantity: ")
      self.Price=int(input("Enter  Price of food: "))
      self.Discount=int(input("Enter Discount: "))
      self.stock=int(input("Enter the available stock: "))
      self.items={"Name":self.Name,"Quantity":self.Quantity,"Price":self.Price,"Discount":self.Discount,"Stock":self.stock}
      self.Food_id=len(self.Foods)+1
      self.Foods[self.Food_id] = self.items
      print("\n!!*****Food Item Added successfully******")
      print("Newly Added Item",self.Foods)
    except:
      print("something went wrong please try again")
  def Edit_food_item(self):
    try:
      x=int(input("Enter the Food id you want to update: "))
      if x in self.Foods.keys():
       print("1 Update Food Name")
       print("2 Update Quantity")
       print("3 Update Price")
       print("4 Update Discount")
       print("5 update stock")

       y=input("Enter Your choice(Enter The number only): ")
       if y == "1":
         self.Foods[x]["Name"] = input("Updated Food Name: ")
         print("successfully Updated Food Name")
       elif y=="2":
         self.Foods[x]["Quantity"] = input("Updated Quantity is: ")
         print("successfully Updated the Quantity")
       elif y=="3":
         self.Foods[x]["Price"]=int(input("Updated Price is: "))
         print("successfully Updated The Price")
       elif y=="4":
         self.Foods[x]["Discount"]=int(input("Updated Discount is: "))
         print("successfully Updated Discount Amount")
       elif y=="5":
         self.Foods[x]["stock"]=int(input("Updated stock is: "))
         print("successfully Updated The stock")
       else:
         print("Sorry  invalid Choice")
      else:
        print("Incorrect Food id ")
        print("Please try Again!!")
    except:
      print("something went wrong plese try again")

  def view_food_item(self):
    print("List of Food Items: ")
    if len(self.Foods)!=0:
      for i in self.Foods:
        print(f"Food Id:{i}")
        for j in self.Foods[i]:
          print(j,":",self.Foods[i][j])
    else:
      print("!!sorry No Food item is Added!!")
  def Delete_food_item(self):
    try:
      x=int(input("Enter the Food Id what you want to Delete: "))
      if x in self.Foods.keys():
        del self.Foods[x]
        print("Food item Deleted successfully")
        print("Remaining Foods Items",self.Foods)
      else:
        print("Incorrect Food Id")
    except:
      print("somethimg went wrong please try again")


      print("*********************************************************************************") 

#USER PART
  def user_register(self):
    try:
      while True:

        print("Please Enter your Email id: ")
        email=input("Enter your email: ")
        print("Enter your Password: ")
        password=input("Enter your password: ")
        res1 = re.findall("^.*(?=.{8,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$",password)
        if res1:
          print("strong password")
        else:
          print("your password is too weak")
          break
        user_name = input("Enter your Name: ")
        phone_no = int(input("Enter your 10 digit phone number: "))
        address = input("Enter your address: ")
        self.user_details = {"user name":user_name,"phone no":phone_no,"Email Id":email,"password":password,"Address":address}
        print("your Account is created successfully")
        
        print("user Details: ")
        for i in self.user_details:
           print(i,":",self.user_details[i])
        break

    except:
      print("somthing went wrong please try again")

  def user_login(self):
    try:
      while True:
        print("welcome To" , self.rest_name)
        email = input("Enter your Email Id: ")
        pas = input("Enter your password: ")
        if len(self.user_details)!=0:
          if email == self.user_details["Email Id"] and pas == self.user_details["password"]:
            print("Login successfully")

            while True:
              print("Hello")
              print("Enter The Below Option")
              print(" 1  Place New Order")
              print(" 2  Check Order History")
              print(" 3  Update Your Profile Details")
              print(" 4  Exit")

              z = input("Enter The Option What You Want")
              if z=="1":
                self.place_order()
              elif z=="2":
                self.ordered_history()
              elif z=="3":
                self.self.update_details()
              elif z=="4":
                break
              else:
                print("Invalid Number")
          else:
              print("invalid email or password")
        else:
            print("There is no Account with this email id !! please create your Account first")
            break
        break
    except:
        print("something went to wrong please try again!!")

  def place_order(self):
    try:
      if len(self.Foods) !=0:
        menu =[]
        for items in self.Foods:
          menu.append([self.Foods[items]["Name"],self.Foods[items]["Quantity"],self.Foods[items]["Price"]])
        for i in menu:
            print(i)
        while True:
            print("Enter 1  Place The order ")
            print("Enter 2  To Exit")
            x=input()
            if x =="1":
              print("Enter The Food Number You want To Ordered separated By comma")
              y = input().split(",")
              for i in y:
                z = int(i)
                if z <= len(menu):
                  self.ordered_item.append(menu[z -1])
                else:
                  print("we Dont't have this Food item: ",z)
              print("List of Food item you selected: ")
              for j in self.ordered_item:
                print(j)
            elif x=="2":
              break
            else:
              print("Invalid Number")
      else:
          print("sorry! No Food item are available Now")
    except:
        print("something went to wrong try again!!")

  def ordered_history(self):

    print("List of previous ordered")
    for i in self.ordered_item:
       print(i)

  def update_details(self):
     try:
       while True:
         print("select below option to update your profile details ")
         print(" 1 Name")
         print(" 2 Phone Number")
         print(" 3 Email Id")
         print(" 4 Password")
         print(" 5 Address")
         print(" 6 Exit")
         x = input("please choose what you want to update ")
         if x =="1":
           self.user_details["user name"]=input("Enter your updated Full Name: ")
           print("Name Updated successfully")
         elif x=="2":
           self.user_details["Phone No."]=int(input("Enter your updated 10 digit phone number: "))
           print("Phone Number updated successfully")
         elif x=="3":
            self.user_details["Email Id"]=input("Enter your updated Email Id: ")
            print("Email updated successfully")
         elif x=="4":
            self.user_details["Password"]=input("Enter your Updated Password:")
            print("Password updated successfully")
         elif x=="5":
            self.user_details["Address"]=input("Enter your updated address with zip code: ")
            print("Address updated succesfully")
         elif x=="6":
            break
         else:
            print("Invalid Number Entered")
         if x in ["1","2","3","4","5"]:
            for i in self.user_details:
              print(i, ":",self.user_details[i])
         else:
            print("please Enter correct input!!")
     except:
        print("something went wrong please try again!!!")


# MAIN PART
   
  def main(self):
    try:
       while True:
         print(" 1 Admin ")
         print(" 2 User ")
         print(" 3 Exit ")
         x = input(" Please Enter the Number: ")
         if x== "1":
           read = open("admin.json","r")
           data = json.load(read)
           print(" For Admin Id and Password please Refer to the json.admin.file")
           name =input("Enter Admin Name: ")
           password = input("Enter Admin password: ")
           if name ==data["Admin name"] and password == data["Admin password"]:
             print("Loged in successfully")
             while True:
               print(" 1 Add New Food Items")
               print(" 2 Edit Food Items")
               print(" 3 view Food Items")
               print(" 4 Delete Food Items")
               print(" 5  Exit")
               y = input("please Enter what you Want: ")
               if y =="1":
                 obj.add_foods_item()
               elif y =="2":
                  obj.Edit_food_item()
               elif y =="3":
                  obj.view_food_item()
               elif y =="4":
                  obj.Delete_food_item()
               elif y=="5":
                  break
               else:
                  print("Invalid Number")
         elif x=="2":
           while True:
               print("Enter the Below Option")
               print(" 1 Register")
               print(" 2  Login")
               print(" 3  Exit")
               y = input("Enter The Number what you want")
               if y =="1":
                 obj.user_register()
               elif y =="2":
                 obj.user_login()
               elif y =="3":
                 break
               else:
                 print("invalid Number")
         elif x=="3":

              print(" ******** Thank you***********")
              print("*******PLease visit again******")
              break
         else:
             print("Invalid Number")
    except:
          print("something went to wrong please give input Carefully")
obj=Restaurant("sahi darbar")
obj.add_food_item()
obj.add_food_item()
obj.add_food_item()
obj.Edit_food_item()
obj.view_food_item()
obj.Delete_food_item()
obj.user_register()
obj.user_login()
obj.place_order()
obj.ordered_history()
obj.main()